# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


# Docker image for arm64v8
stages: 
- stage: BuildOnArm64
  jobs:
  - job: Build
    pool: 
      name: SH-Mypool
      demands: Agent.Name -equals ubuntu_arm64
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'svc_dockerhub'
        repository: 'mmsajid/devops-arm64'
        tags: |
         latest
         $(Build.BuildId)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile-arm64'
        arguments: '--platform linux/arm64'

# Docker image for x64
- stage: BuildOnx64
  jobs:
  - job: Build
    pool:
      name: SH-Mypool
      demands: Agent.Name -equals ubuntu_x86_64
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'svc_dockerhub'
        repository: 'mmsajid/devops-x86_64'
        tags: |
         latest
         $(Build.BuildId)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        arguments: '--platform linux/amd64'